"""Added Battaries and Cells tables

Revision ID: 5964564d5673
Revises: 35605900b320
Create Date: 2026-04-09 13:50:11.184002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5964564d5673'
down_revision: Union[str, Sequence[str], None] = '35605900b320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batteries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('time_charged', sa.Time(), nullable=False),
    sa.Column('time_discharged', sa.Time(), nullable=False),
    sa.Column('tested_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batteries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batteries_barcode'), ['barcode'], unique=True)
        batch_op.create_index(batch_op.f('ix_batteries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batteries_type'), ['type'], unique=True)

    op.create_table('cells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('time_charged', sa.Time(), nullable=False),
    sa.Column('time_discharged', sa.Time(), nullable=False),
    sa.Column('tested_at', sa.Date(), nullable=False),
    sa.Column('battery_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['battery_id'], ['batteries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cells', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cells_barcode'), ['barcode'], unique=True)
        batch_op.create_index(batch_op.f('ix_cells_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cells_type'), ['type'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cells', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cells_type'))
        batch_op.drop_index(batch_op.f('ix_cells_id'))
        batch_op.drop_index(batch_op.f('ix_cells_barcode'))

    op.drop_table('cells')
    with op.batch_alter_table('batteries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batteries_type'))
        batch_op.drop_index(batch_op.f('ix_batteries_id'))
        batch_op.drop_index(batch_op.f('ix_batteries_barcode'))

    op.drop_table('batteries')
    # ### end Alembic commands ###
