"""Added Product models table

Revision ID: b0f1c8c0065e
Revises: 5964564d5673
Create Date: 2026-04-13 12:58:03.409318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f1c8c0065e'
down_revision: Union[str, Sequence[str], None] = '5964564d5673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('BATTERY', 'CELL', name='producttypes'), nullable=False),
    sa.Column('voltage', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_models')),
    sa.UniqueConstraint('number', name=op.f('uq_product_models_number'))
    )
    with op.batch_alter_table('batteries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_model_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_batteries_type'))
        batch_op.create_foreign_key(batch_op.f('fk_batteries_product_model_id_product_models'), 'product_models', ['product_model_id'], ['id'])
        batch_op.drop_column('type')

    with op.batch_alter_table('cells', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_model_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_cells_type'))
        batch_op.create_foreign_key(batch_op.f('fk_cells_product_model_id_product_models'), 'product_models', ['product_model_id'], ['id'])
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cells', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_cells_product_model_id_product_models'), type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_cells_type'), ['type'], unique=1)
        batch_op.drop_column('product_model_id')

    with op.batch_alter_table('batteries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_batteries_product_model_id_product_models'), type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_batteries_type'), ['type'], unique=1)
        batch_op.drop_column('product_model_id')

    op.drop_table('product_models')
    # ### end Alembic commands ###
